name: auto_merge
on:
  pull_request:
    branches:
      - main

jobs:
  auto_merge:
    runs-on: ubuntu-latest
    steps:
      - uses: KeisukeYamashita/auto-pull-request-merge@v1
        with:
          intervalSeconds: 10
          timeoutSeconds: 30
          token: ${{ secrets.TOKEN_GITHUB }}